/*
 * MONICA COP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using COP.API.Attributes;

using Microsoft.AspNetCore.Authorization;
using COP.API.Models;

namespace COP.API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class NoiseCaptureApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>get nose capture</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Error</response>
        [HttpGet]
        [Route("//noiseCapture")]
        [ValidateModelState]
        [SwaggerOperation("NoiseCaptureGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NoiseCaptureMeta), description: "Success")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult NoiseCaptureGet()
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NoiseCaptureMeta));

            OGCSensorThings.NoiseCaptureMetaOGC m = new OGCSensorThings.NoiseCaptureMetaOGC();
            NoiseCaptureMeta ncm = m.GetNCMeta();
            return new ObjectResult(ncm);
        }
    }
}
