/*
 * MONICA COP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using COP.API.Attributes;
using COP.API.Models;

namespace COP.API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class PersonWithWearablesApiController : Controller
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>ListAllWearables</remarks>
        /// <param name="role"></param>
        /// <response code="200">Success</response>
        /// <response code="0">Error</response>
        [HttpGet]
        [Route("/peoplewithwearables")]
        [ValidateModelState]
        [SwaggerOperation("PeoplewithwearablesGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetPwwListResponse), description: "Success")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult PeoplewithwearablesGet([FromQuery]string role, [FromHeader][Required()]string Authorization)
        {
            if (!ModelState.IsValid)
            {
                var error = ModelState.SelectMany(x => x.Value.Errors).First();
                if (error.ErrorMessage != null && error.ErrorMessage != String.Empty)
                {
                    return BadRequest(error.ErrorMessage);
                }
                else if (error.Exception?.Message != null)
                {
                    return BadRequest("Faulty input");
                }
                else
                    return BadRequest(ModelState);

            }
            if (Authorization != settings.testToken)
                return BadRequest("Not allowed");
            long newZoneID = 0;
            string errorMessage = "";
            List<PersonWithWearable> results = new List<PersonWithWearable>();
            try
            {
                DatabaseInterface.DBPersonWithWearablesApi dBPersonWithWearablesApi = new DatabaseInterface.DBPersonWithWearablesApi();
                if (!dBPersonWithWearablesApi.ListPersonWithWearables(role, ref errorMessage, ref results))
                    return BadRequest("Internal Server Error:" + errorMessage);

            }
            catch (Exception e)
            {
                return BadRequest("Internal Server Error:" + e.Message);
            }

            string exampleJson = null;

            return new ObjectResult(results);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>get zone by id</remarks>
        /// <param name="personId"></param>
        /// <response code="200">Success</response>
        /// <response code="0">Error</response>
        [HttpGet]
        [Route("/peoplewithwearables/{personId}")]
        [ValidateModelState]
        [SwaggerOperation("PeoplewithwearablesPersonIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(PersonWithWearable), description: "Success")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult PeoplewithwearablesPersonIdGet([FromRoute][Required]string personId, [FromHeader][Required()]string Authorization)
        {
            if (!ModelState.IsValid)
            {
                var error = ModelState.SelectMany(x => x.Value.Errors).First();
                if (error.ErrorMessage != null && error.ErrorMessage != String.Empty)
                {
                    return BadRequest(error.ErrorMessage);
                }
                else if (error.Exception?.Message != null)
                {
                    return BadRequest("Faulty input");
                }
                else
                    return BadRequest(ModelState);

            }
            if (Authorization != settings.testToken)
                return BadRequest("Not allowed");
            long newZoneID = 0;
            string errorMessage = "";
           PersonWithWearable result = null;
            try
            {
                DatabaseInterface.DBPersonWithWearablesApi dBPersonWithWearablesApi = new DatabaseInterface.DBPersonWithWearablesApi();
                if (!dBPersonWithWearablesApi.ListPersonByIdWithWearables(int.Parse(personId), ref errorMessage, ref result))
                    return BadRequest("Internal Server Error:" + errorMessage);

            }
            catch (Exception e)
            {
                return BadRequest("Internal Server Error:" + e.Message);
            }

            string exampleJson = null;

            return new ObjectResult(result);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>get zone by id</remarks>
        /// <param name="personId"></param>
        /// <param name="message">Message</param>
        /// <response code="200">Success</response>
        /// <response code="0">Error</response>
        [HttpPost]
        [Route("/peoplewithwearables/{personId}/SendMessage")]
        [ValidateModelState]
        [SwaggerOperation("PeoplewithwearablesPersonIdSendMessagePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(GeneralResponse), description: "Success")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult PeoplewithwearablesPersonIdSendMessagePost([FromRoute][Required]string personId, [FromBody] TextMessage message, [FromHeader][Required()]string Authorization)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(GeneralResponse));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorResponse));


            if (!ModelState.IsValid)
            {
                var error = ModelState.SelectMany(x => x.Value.Errors).First();
                if (error.ErrorMessage != null && error.ErrorMessage != String.Empty)
                {
                    return BadRequest(error.ErrorMessage);
                }
                else if (error.Exception?.Message != null)
                {
                    return BadRequest("Faulty input");
                }
                else
                    return BadRequest(ModelState);

            }
            if (Authorization != settings.testToken)
                return BadRequest("Not allowed");
            long newZoneID = 0;
            string errorMessage = "";
            PersonWithWearable result = null;
            try
            {
                DatabaseInterface.DBPersonWithWearablesApi dBPersonWithWearablesApi = new DatabaseInterface.DBPersonWithWearablesApi();
                if (!dBPersonWithWearablesApi.DBSendPersonMessage(personId, message.Message, ref errorMessage))
                    return BadRequest("Internal Server Error:" + errorMessage);

            }
            catch (Exception e)
            {
                return BadRequest("Internal Server Error:" + e.Message);
            }

            string exampleJson = null;

            exampleJson = "{\n  \"success\" : true,\n  \"description\" : \"Message sent\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GeneralResponse>(exampleJson)
            : default(GeneralResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <remarks>get zone by id</remarks>
        /// <param name="personId"></param>
        /// <param name="message">Message</param>
        /// <response code="200">Success</response>
        /// <response code="0">Error</response>
        [HttpPost]
        [Route("/peoplewithwearables/{personId}/SendMediaMessage")]
        [ValidateModelState]
        [SwaggerOperation("PeoplewithwearablesPersonIdSendMediaMessagePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(GeneralResponse), description: "Success")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult PeoplewithwearablesPersonIdSendMediaMessagePost([FromRoute][Required]string personId, [FromBody] MediaMessage message, [FromHeader][Required()]string Authorization)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(GeneralResponse));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorResponse));


            if (!ModelState.IsValid)
            {
                var error = ModelState.SelectMany(x => x.Value.Errors).First();
                if (error.ErrorMessage != null && error.ErrorMessage != String.Empty)
                {
                    return BadRequest(error.ErrorMessage);
                }
                else if (error.Exception?.Message != null)
                {
                    return BadRequest("Faulty input");
                }
                else
                    return BadRequest(ModelState);

            }
            if (Authorization != settings.testToken)
                return BadRequest("Not allowed");
            long newZoneID = 0;
            string errorMessage = "";
            PersonWithWearable result = null;
            try
            {
                DatabaseInterface.DBPersonWithWearablesApi dBPersonWithWearablesApi = new DatabaseInterface.DBPersonWithWearablesApi();
                if (!dBPersonWithWearablesApi.DBSendPersonMediaMessage(personId, message.MediaLink, message.MediaType, ref errorMessage))
                    return BadRequest("Internal Server Error:" + errorMessage);

            }
            catch (Exception e)
            {
                return BadRequest("Internal Server Error:" + e.Message);
            }

            string exampleJson = null;

            exampleJson = "{\n  \"success\" : true,\n  \"description\" : \"Message sent\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GeneralResponse>(exampleJson)
            : default(GeneralResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
