/*
 * MONICA COP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using COP.API.Attributes;
using COP.API.Models;
using Microsoft.AspNetCore.SignalR;

namespace COP.API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class XHUBMessageApiController : Controller
    {
        private readonly IHubContext<EventHubs.WearableUpdate> _hubContext;

        public XHUBMessageApiController(IHubContext<EventHubs.WearableUpdate> hubContext)
        {
            _hubContext = hubContext;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>add a new message</remarks>
        /// <param name="message">message</param>
        /// <response code="200">Success</response>
        /// <response code="0">Error</response>
        [HttpPost]
        [Route("//HUBMessage")]
        [DisableRequestSizeLimit]
        [ValidateModelState]
        [SwaggerOperation("HUBMessagePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(GeneralResponse), description: "Success")]
        [SwaggerResponse(statusCode: 0, type: typeof(ErrorResponse), description: "Error")]
        public virtual IActionResult HUBMessagePost([FromBody]HUBmessage message, [FromHeader] string Authorization)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(GeneralResponse));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(ErrorResponse));
            _hubContext.Clients.All.SendAsync(message.Action, message.Message);
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"description\" : \"description\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<GeneralResponse>(exampleJson)
            : default(GeneralResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
